# Generated by Django 5.2.11 on 2026-02-25 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('callback_requested', 'Callback Requested'), ('needs_human', 'Needs Human')], max_length=20)),
                ('qualified', models.BooleanField()),
                ('score', models.PositiveSmallIntegerField(help_text='0–100')),
                ('reasoning', models.TextField()),
                ('callback_requested', models.BooleanField(default=False)),
                ('callback_notes', models.TextField(blank=True, null=True)),
                ('needs_human', models.BooleanField(default=False)),
                ('needs_human_notes', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField()),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='applications.application')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='calls.call')),
            ],
            options={
                'verbose_name': 'LLM Evaluation',
                'verbose_name_plural': 'LLM Evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
