# Generated by Django 5.2.11 on 2026-02-25 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_call', 'Pending Call'), ('call_queued', 'Call Queued'), ('call_in_progress', 'Call In Progress'), ('call_completed', 'Call Completed'), ('call_failed', 'Call Failed'), ('scoring', 'Scoring'), ('qualified', 'Qualified'), ('awaiting_cv', 'Awaiting CV'), ('cv_followup_1', 'CV Follow-up 1'), ('cv_followup_2', 'CV Follow-up 2'), ('cv_overdue', 'CV Overdue'), ('cv_received', 'CV Received'), ('not_qualified', 'Not Qualified'), ('awaiting_cv_rejected', 'Awaiting CV (Rejected)'), ('cv_received_rejected', 'CV Received (Rejected)'), ('callback_scheduled', 'Callback Scheduled'), ('needs_human', 'Needs Human'), ('closed', 'Closed')], default='pending_call', max_length=30)),
                ('qualified', models.BooleanField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_notes', models.TextField(blank=True, null=True)),
                ('cv_received_at', models.DateTimeField(blank=True, null=True)),
                ('callback_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('needs_human_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='positions.position')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'position')},
            },
        ),
    ]
