# Generated by Django 5.2.11 on 2026-02-25 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending_call', 'Pending Call'), ('call_queued', 'Call Queued'), ('call_in_progress', 'Call In Progress'), ('call_completed', 'Call Completed'), ('call_failed', 'Call Failed'), ('scoring', 'Scoring'), ('qualified', 'Qualified'), ('awaiting_cv', 'Awaiting CV'), ('cv_followup_1', 'CV Follow-up 1'), ('cv_followup_2', 'CV Follow-up 2'), ('cv_overdue', 'CV Overdue'), ('cv_received', 'CV Received'), ('not_qualified', 'Not Qualified'), ('awaiting_cv_rejected', 'Awaiting CV (Rejected)'), ('cv_received_rejected', 'CV Received (Rejected)'), ('callback_scheduled', 'Callback Scheduled'), ('needs_human', 'Needs Human'), ('closed', 'Closed')], max_length=30)),
                ('to_status', models.CharField(choices=[('pending_call', 'Pending Call'), ('call_queued', 'Call Queued'), ('call_in_progress', 'Call In Progress'), ('call_completed', 'Call Completed'), ('call_failed', 'Call Failed'), ('scoring', 'Scoring'), ('qualified', 'Qualified'), ('awaiting_cv', 'Awaiting CV'), ('cv_followup_1', 'CV Follow-up 1'), ('cv_followup_2', 'CV Follow-up 2'), ('cv_overdue', 'CV Overdue'), ('cv_received', 'CV Received'), ('not_qualified', 'Not Qualified'), ('awaiting_cv_rejected', 'Awaiting CV (Rejected)'), ('cv_received_rejected', 'CV Received (Rejected)'), ('callback_scheduled', 'Callback Scheduled'), ('needs_human', 'Needs Human'), ('closed', 'Closed')], max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Change',
                'verbose_name_plural': 'Status Changes',
                'ordering': ['-changed_at'],
            },
        ),
    ]
