# Generated by Django 5.2.11 on 2026-02-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_callback_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending_call', 'Pending Call'), ('call_queued', 'Call Queued'), ('call_in_progress', 'Call In Progress'), ('call_completed', 'Call Completed'), ('call_failed', 'Call Failed'), ('scoring', 'Scoring'), ('qualified', 'Qualified'), ('awaiting_cv', 'Awaiting CV'), ('cv_followup_1', 'CV Follow-up 1'), ('cv_followup_2', 'CV Follow-up 2'), ('cv_overdue', 'CV Overdue'), ('cv_received', 'CV Received'), ('not_qualified', 'Not Qualified'), ('awaiting_cv_rejected', 'Awaiting CV – Not Qualified'), ('cv_received_rejected', 'CV Received – Not Qualified'), ('callback_scheduled', 'Callback Scheduled'), ('needs_human', 'Needs Human'), ('closed', 'Closed')], db_index=True, default='pending_call', max_length=30),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='from_status',
            field=models.CharField(choices=[('pending_call', 'Pending Call'), ('call_queued', 'Call Queued'), ('call_in_progress', 'Call In Progress'), ('call_completed', 'Call Completed'), ('call_failed', 'Call Failed'), ('scoring', 'Scoring'), ('qualified', 'Qualified'), ('awaiting_cv', 'Awaiting CV'), ('cv_followup_1', 'CV Follow-up 1'), ('cv_followup_2', 'CV Follow-up 2'), ('cv_overdue', 'CV Overdue'), ('cv_received', 'CV Received'), ('not_qualified', 'Not Qualified'), ('awaiting_cv_rejected', 'Awaiting CV – Not Qualified'), ('cv_received_rejected', 'CV Received – Not Qualified'), ('callback_scheduled', 'Callback Scheduled'), ('needs_human', 'Needs Human'), ('closed', 'Closed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='to_status',
            field=models.CharField(choices=[('pending_call', 'Pending Call'), ('call_queued', 'Call Queued'), ('call_in_progress', 'Call In Progress'), ('call_completed', 'Call Completed'), ('call_failed', 'Call Failed'), ('scoring', 'Scoring'), ('qualified', 'Qualified'), ('awaiting_cv', 'Awaiting CV'), ('cv_followup_1', 'CV Follow-up 1'), ('cv_followup_2', 'CV Follow-up 2'), ('cv_overdue', 'CV Overdue'), ('cv_received', 'CV Received'), ('not_qualified', 'Not Qualified'), ('awaiting_cv_rejected', 'Awaiting CV – Not Qualified'), ('cv_received_rejected', 'CV Received – Not Qualified'), ('callback_scheduled', 'Callback Scheduled'), ('needs_human', 'Needs Human'), ('closed', 'Closed')], max_length=30),
        ),
    ]
