# Generated by Django 5.2.11 on 2026-02-25 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('email_attachment', 'Email Attachment'), ('whatsapp_media', 'WhatsApp Media'), ('manual_upload', 'Manual Upload')], max_length=20)),
                ('match_method', models.CharField(blank=True, choices=[('exact_email', 'Exact Email'), ('exact_phone', 'Exact Phone'), ('subject_id', 'Subject ID'), ('fuzzy_name', 'Fuzzy Name'), ('cv_content', 'CV Content Extraction'), ('manual', 'Manual Assignment')], max_length=20, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_uploads', to='applications.application')),
            ],
            options={
                'verbose_name': 'CV Upload',
                'verbose_name_plural': 'CV Uploads',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='UnmatchedInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body_snippet', models.TextField(blank=True, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unmatched_inbounds', to='applications.application')),
            ],
            options={
                'verbose_name': 'Unmatched Inbound',
                'verbose_name_plural': 'Unmatched Inbounds',
                'ordering': ['-received_at'],
            },
        ),
    ]
