# Generated by Django 5.2.11 on 2026-02-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvupload',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='unmatchedinbound',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
