# Generated by Django 5.2.11 on 2026-02-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('cvs', '0002_alter_cvupload_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvupload',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_uploads', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='unmatchedinbound',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cvupload',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
