# Generated by Django 5.2.11 on 2026-02-25 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('eleven_labs_conversation_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_url', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='applications.application')),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
