# Generated by Django 5.2.11 on 2026-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed')], default='open', max_length=10)),
                ('campaign_questions', models.TextField()),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('first_message', models.TextField(blank=True, null=True)),
                ('qualification_prompt', models.TextField(blank=True, null=True)),
                ('call_retry_max', models.PositiveSmallIntegerField(default=2, help_text='Max call attempts before marking the application call_failed.')),
                ('call_retry_interval_minutes', models.PositiveIntegerField(default=60, help_text='Minutes to wait between retry attempts.')),
                ('calling_hour_start', models.PositiveSmallIntegerField(default=10, help_text='Earliest hour to place calls (24-hour format).')),
                ('calling_hour_end', models.PositiveSmallIntegerField(default=18, help_text='Latest hour to place calls (24-hour format).')),
                ('follow_up_interval_hours', models.PositiveIntegerField(default=24, help_text='Hours between CV follow-up messages for qualified candidates.')),
                ('rejected_cv_timeout_days', models.PositiveSmallIntegerField(default=7, help_text="Days to wait for a rejected candidate's CV before closing the application.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-created_at'],
            },
        ),
    ]
