# Generated by Django 5.2.11 on 2026-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='position',
            name='contact_type',
            field=models.CharField(blank=True, default='', help_text='Comma-separated contact types: cim, b2b', max_length=20),
        ),
        migrations.AddField(
            model_name='position',
            name='salary_range',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
