# Generated by Django 5.2.11 on 2026-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=300)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('email', models.CharField(db_index=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('meta_form', 'Meta Form'), ('manual', 'Manual')], default='meta_form', max_length=20)),
                ('meta_lead_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('meta_created_time', models.DateTimeField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=20, null=True)),
                ('form_answers', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
