# Generated by Django 5.2.11 on 2026-02-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_candidate_reply'),
        ('candidates', '0001_initial'),
        ('messaging', '0002_alter_message_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=10)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_replies', to='applications.application')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Candidate Reply',
                'verbose_name_plural': 'Candidate Replies',
                'ordering': ['-received_at'],
            },
        ),
    ]
