# Generated by Django 5.2.11 on 2026-02-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_candidate_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('cv_request', 'CV Request (Qualified)'), ('cv_request_rejected', 'CV Request (Not Qualified)'), ('cv_followup_1', 'CV Follow-up 1'), ('cv_followup_2', 'CV Follow-up 2'), ('rejection', 'Rejection')], db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['message_type', 'channel'],
                'unique_together': {('message_type', 'channel')},
            },
        ),
    ]
