from django.db import models
from django.utils import timezone


class Call(models.Model):
    """
    One record per call attempt. Multiple attempts are possible per Application
    (up to Position.call_retry_max).
    """

    class Status(models.TextChoices):
        INITIATED = "initiated", "Initiated"
        IN_PROGRESS = "in_progress", "In Progress"
        COMPLETED = "completed", "Completed"
        NO_ANSWER = "no_answer", "No Answer"
        BUSY = "busy", "Busy"
        FAILED = "failed", "Failed"

    application = models.ForeignKey(
        "applications.Application",
        on_delete=models.CASCADE,
        related_name="calls",
    )
    attempt_number = models.PositiveSmallIntegerField()

    # Returned by ElevenLabs on call initiation — used to match webhook events
    eleven_labs_conversation_id = models.CharField(
        max_length=255,
        unique=True,
        null=True,
        blank=True,
    )

    # Returned by ElevenLabs batch-calling API — groups all calls in a batch submission
    eleven_labs_batch_id = models.CharField(max_length=100, null=True, blank=True)

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.INITIATED,
        db_index=True,
    )

    # Full conversation transcript formatted as "Agent: ...\nUser: ..."
    # Sent to Claude for qualification scoring.
    transcript = models.TextField(null=True, blank=True)

    # Auto-generated by ElevenLabs post-call analysis
    summary = models.TextField(null=True, blank=True)
    summary_title = models.CharField(max_length=255, null=True, blank=True)

    recording_url = models.CharField(max_length=500, null=True, blank=True)
    duration_seconds = models.PositiveIntegerField(null=True, blank=True)

    initiated_at = models.DateTimeField(default=timezone.now)
    ended_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-initiated_at"]
        verbose_name = "Call"
        verbose_name_plural = "Calls"

    def __str__(self) -> str:
        return f"Call #{self.attempt_number} [{self.status}] — {self.application}"
